import turtle
'''
Project 1 - Turtle Art - Spring 2022
Author: Ethan Leinberger Lethan20

This program uses turtle graphics to generate a drawing of a volcano
erupting during a sunset.

I have neither given or received unauthorized assistance on this assignment.
Signed:  Ethan Leinberger
'''
turtle.setup(700, 650)
turtle.title('Project 1 - Turtle Art - Ethan Leinberger')

turtle.speed(0)
turtle.bgcolor('skyblue')

#Drawing the border
turtle.penup()
turtle.goto(-350, 314)
turtle.pendown()
turtle.pencolor('maroon')
turtle.pensize(18)
turtle.forward(682)
turtle.right(90)
turtle.forward(622)
turtle.right(90)
turtle.forward(674)
turtle.right(90)
turtle.forward(624)

#draw sunset top layer
turtle.penup()
turtle.goto(-332, 305)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('#4C3F91')
turtle.setheading(0)
turtle.fillcolor('#4C3F91')
turtle.begin_fill()
turtle.forward(652)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(652)
turtle.right(90)
turtle.forward(150)
turtle.end_fill()

#draw sunset third layer
turtle.penup()
turtle.goto(-332, 155)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('#9145B6')
turtle.setheading(0)
turtle.fillcolor('#9145B6')
turtle.begin_fill()
turtle.forward(652)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(652)
turtle.right(90)
turtle.forward(140)
turtle.end_fill()

#draw sunset second layer
turtle.penup()
turtle.goto(-332, 10)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('#B958A5')
turtle.setheading(0)
turtle.fillcolor('#B958A5')
turtle.begin_fill()
turtle.forward(652)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(652)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()

#draw pink sunset bottom layer
turtle.penup()
turtle.goto(-332, -110)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('#FF5677')
turtle.setheading(0)
turtle.fillcolor('#FF5677')
turtle.begin_fill()
turtle.forward(652)
turtle.right(90)
turtle.forward(95)
turtle.right(90)
turtle.forward(652)
turtle.right(90)
turtle.forward(95)
turtle.end_fill()

#draw sun
turtle.penup()
turtle.goto(-190, -170)
turtle.pencolor('coral')
turtle.pendown()
turtle.fillcolor('coral')
turtle.begin_fill()
turtle.circle(70)
turtle.end_fill()

#draw grass
turtle.penup()
turtle.goto(-332, -210)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('green')
turtle.setheading(0)
turtle.fillcolor('green')
turtle.begin_fill()
turtle.forward(652)
turtle.right(90)
turtle.forward(85)
turtle.right(90)
turtle.forward(652)
turtle.right(90)
turtle.forward(85)
turtle.end_fill()

#volcano outline
turtle.penup()
turtle.goto(-220, -210)
turtle.pendown()
turtle.pencolor('grey')
turtle.setheading(70)
turtle.fillcolor('grey')
turtle.begin_fill()
turtle.forward(200)
turtle.right(100)
turtle.forward(40)
turtle.left(100)
turtle.forward(150)
turtle.setheading(270)
turtle.circle(50, extent= 180)
turtle.setheading(290)
turtle.forward(150)
turtle.left(100)
turtle.forward(40)
turtle.right(100)
turtle.forward(200)
turtle.setheading(180)
turtle.forward(410)
turtle.end_fill()

#outline lower mountain of volcano
turtle.penup()
turtle.goto(-180, -210)
turtle.pendown()
turtle.pencolor('black')
turtle.setheading(80)
turtle.forward(75)
turtle.right(115)
turtle.forward(15)
turtle.left(80)
turtle.forward(35)
turtle.right(100)
turtle.forward(95)
turtle.left(100)
turtle.forward(100)
turtle.right(50)
turtle.forward(30)
turtle.left(90)
turtle.forward(90)
turtle.right(80)
turtle.forward(50)

turtle.penup()
turtle.goto(120, -210)
turtle.setheading(135)
turtle.pendown()
turtle.forward(100)
turtle.left(60)
turtle.forward(40)
turtle.right(70)
turtle.forward(90)
turtle.left(95)
turtle.forward(120)
turtle.left(30)
turtle.forward(62)


#draw lava

#circle at the top
turtle.penup()
turtle.goto(-70,100)
turtle.pencolor('red')
turtle.fillcolor('red')
turtle.begin_fill()
turtle.pendown()
turtle.setheading(270)
turtle.circle(50, extent=180)
turtle.setheading(180)
turtle.forward(100)
turtle.end_fill()

#first strand going down on left of mountain
turtle.setheading(250)
turtle.forward(90)
turtle.left(30)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(20)
turtle.forward(50)
turtle.left(20)
turtle.forward(45)
turtle.right(30)
turtle.forward(100)
turtle.right(40)
turtle.forward(60)

#orange strand alongside
turtle.penup()
turtle.goto(-65,100)
turtle.pencolor('orange')
turtle.pendown()
turtle.setheading(250)
turtle.forward(90)
turtle.left(30)
turtle.forward(100)
turtle.left(45)
turtle.forward(100)
turtle.left(20)
turtle.forward(50)
turtle.left(20)
turtle.forward(45)
turtle.right(30)
turtle.forward(100)
turtle.right(40)
turtle.forward(60)


#following black lower mountain outline
turtle.penup()
turtle.goto(-190, -210)
turtle.pendown()
turtle.pencolor('red')
turtle.setheading(80)
turtle.forward(75)
turtle.right(115)
turtle.forward(15)
turtle.left(80)
turtle.forward(35)
turtle.right(100)
turtle.forward(95)
turtle.left(100)
turtle.forward(100)
turtle.right(50)
turtle.forward(30)
turtle.left(90)
turtle.forward(90)
turtle.right(80)
turtle.forward(50)

#following black lower mountain outline
turtle.penup()
turtle.goto(110, -210)
turtle.setheading(135)
turtle.pendown()
turtle.forward(100)
turtle.left(60)
turtle.forward(40)
turtle.right(70)
turtle.forward(90)
turtle.left(95)
turtle.forward(120)
turtle.left(30)
turtle.forward(62)

# strand going down right side of mountain
turtle.penup()
turtle.goto(30, 100)
turtle.pendown()
turtle.setheading(290)
turtle.forward(90)
turtle.right(80)
turtle.forward(60)
turtle.left(60)
turtle.forward(80)
turtle.left(50)
turtle.forward(100)
turtle.left(40)
turtle.forward(40)
turtle.right(80)
turtle.forward(80)
#orange strand alongside
turtle.penup()
turtle.goto(35, 100)
turtle.pencolor('orange')
turtle.pendown()
turtle.setheading(290)
turtle.forward(90)
turtle.right(80)
turtle.forward(60)
turtle.left(60)
turtle.forward(80)
turtle.left(50)
turtle.forward(100)
turtle.left(40)
turtle.forward(40)
turtle.right(80)
turtle.forward(80)

#red strand from center of pit
turtle.penup()
turtle.goto(-40, 50)
turtle.pencolor('red')
turtle.pendown()
turtle.forward(110)
turtle.right(60)
turtle.forward(80)
turtle.left(40)
turtle.forward(90)
turtle.left(20)
turtle.forward(100)

#orange strand alongside
turtle.penup()
turtle.goto(-35, 50)
turtle.pencolor('orange')
turtle.pendown()
turtle.forward(110)
turtle.right(60)
turtle.forward(80)
turtle.left(40)
turtle.forward(90)
turtle.left(20)
turtle.forward(100)

#semicircle inside red circle
turtle.penup()
turtle.goto(-45,85)
turtle.pendown()
turtle.pencolor('orange')
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.pendown()
turtle.setheading(270)
turtle.circle(25, extent=180)
turtle.setheading(180)
turtle.forward(50)
turtle.end_fill()


turtle.done()